elite_bundle_main_controller:
    pattern: /test
    defaults: { _controller: eff.elite_bundle.controller:display }

elite_bundle_member_controller:
    pattern: /member/{id}
    defaults: { _controller: eff.elite_bundle.controller:member, id: 0 }
    requirements:
            id:  \d+
